---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  vars:
    traefik_domain: "tintoy-swarm.net"
    masters_group: role=master
    workers_group: role=worker

  roles:
    - common
    - certificates
    - dnsmasq
    - docker
    - consul

# Configure Docker Swarm after everything else is in place. 
- hosts: all
  roles:
    - docker-swarm
