---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  vars:
    traefik_domain: "tintoy-swarm.net"

  roles:
    - common
    - certificates
    - docker
    - consul
    - docker-swarm

- hosts: role=master
  vars:
    is_master: true
  roles:
    - docker-swarm

- hosts: role=worker
  vars:
    is_worker: true
  roles:
    - docker-swarm

  