---
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

- hosts: all
  vars:
    traefik_domain: "tintoy-swarm.net"
    masters_group: role=master
    workers_group: role=worker

  roles:
    - common
    - certificates
    - docker
    - consul
    - docker-swarm

# Configure Docker Swarm after everything else is in place. 
- hosts: role=master|worker
  vars:
    masters_group: role=master
    workers_group: role=worker
  roles:
    - docker-swarm

  