#!/bin/bash

# Refresh Terraform state
echo "Step 1 of 3 - Refreshing Terraform state..."
pushd ./terraform
terraform refresh
if [ $? -ne 0 ]; then
	echo "Failed to refresh Terraform state."

	popd
fi

popd
echo "Step 1 of 3 complete; Terraform state refreshed."

# Use SSH key file.
echo "Step 2 of 3 - Configuring cluster machines to use SSH keyfile (initial password can be found in terraform/ddcloud-docker-swarm.tf)..."
ansible all -u root -k -m authorized_key -a "user=root key='{{ lookup('file', '$HOME/.ssh/id_rsa.pub') }}'"

echo "Step 2 of 3 complete; SSH keys configured."

# Set host names.
echo "Step 3 of 3 - configuring cluster machine host names..."
ansible all -u root -a "hostnamectl set-hostname {{ inventory_hostname }}" 

echo "Expect errors from the next command since we're rebooting the target servers..."
ansible all -u root -e 'ignore_errors=true' -a 'nohup bash -c "sleep 2s && reboot" &'

echo "Step 3 of 3 complete; wait for reboot before proceeding."
