---
- name: restart consul
  sudo: yes
  command: /usr/local/bin/consul-rolling-restart.sh {{ consul_acl_master_token }}
  notify:
    - wait for consul to listen

- name: reload consul
  sudo: yes
  command: systemctl reload consul
  notify:
    - wait for consul to listen
