---

- name: install dnsmasq
  sudo: yes
  yum:
    name: "dnsmasq"
    state: present
  tags:
    - dnsmasq

- name: update configuration for dnsmasq
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - dnsmasq.conf
    - resolv.dnsmasq.conf
  tags:
    - dnsmasq

- name: update resolv.conf
  sudo: yes
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
  tags:
    - dnsmasq

- name: start dnsmasq
  sudo: yes
  service: name=dnsmasq
           state=restarted
  tags:
    - dnsmasq
