---
- name: enable Docker, Inc. yum repo
  sudo: yes
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
  tags:
    - docker

- name: create rsyslog.d
  sudo: yes
  file:
    dest: /etc/rsyslog.d
    state: directory
  tags:
    - docker

- name: create docker entry for syslogd
  sudo: yes
  copy:
    dest: /etc/rsyslog.d/10-docker.conf
    content: |
      # Docker logging
      :syslogtag, isequal, "docker:"  /var/log/docker/docker.log
      & ~
  notify:
    - restart rsyslog
  tags:
    - docker


- name: create directory for systemd drop-ins
  sudo: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  tags:
    - docker

- name: systemd drop-in for options
  sudo: yes
  template:
    src:  "{{ item }}.j2"
    dest: "/etc/systemd/system/docker.service.d/{{ item }}"
  with_items:
    - 10-options.conf
    - 12-network-options.conf
  notify:
    - reload docker
  tags:
    - docker

- name: systemd drop-in for ExecStart
  sudo: yes
  copy:
    src: 20-ExecStart.conf.j2
    dest: /etc/systemd/system/docker.service.d/20-ExecStart.conf
  notify:
    - reload docker
  tags:
    - docker

# Must install packages in reverse order due to specific dependency version
- name: install docker packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker-engine-selinux-0:{{docker_version}}.el7.centos.noarch"
    - "docker-engine-0:{{docker_version}}.el7.centos.x86_64"
  tags:
    - docker

- name: ensure docker config dir exists
  sudo: yes
  file:
    path: /root/.docker
    state: directory
  tags:
    - docker

- name: enable docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

- name: install latest docker-compose
  sudo: yes
  shell: "curl -L https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"
  tags:
    - docker
