---

- name: create data folder for docker registry
  sudo: true
  file:
    path: "{{registry_data_directory}}/data"
    state: directory
    # owner: docker
    # group: docker
    # mode: "u=rwx,g=rwx,o="
  tags:
      - docker-registry

- name: create auth folder for docker registry
  sudo: true
  file:
    path: "{{registry_data_directory}}/auth"
    state: directory
    # owner: docker
    # group: docker
    # mode: "u=rwx,g=rwx,o="
  tags:
      - docker-registry

- name: create htpasswd for docker registry
  sudo: true
  shell: "htpasswd -nbB '{{registry_user}}' '{{registry_password}}' > '{{registry_data_directory}}/auth/htpasswd'"
  args:
    creates: "{{registry_data_directory}}/auth/htpasswd"
  tags:
    - docker-registry

- name: create registry startup script
  sudo: true
  template:
    src: "start-registry.sh.j2"
    dest: "{{registry_data_directory}}/start-registry.sh"
    mode: "u=rwx,g=rx"
  tags:
    - docker-registry

- name: start or update registry
  sudo: true
  shell: "{{registry_data_directory}}/start-registry.sh"
  tags:
    - docker-registry
