---
- hosts: all
  gather_facts: no
  tasks:
    - name: restart server
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      sudo: true

      async: 1
      poll: 0

      ignore_errors: true

    - name: waiting for server to restart
      local_action: wait_for
                    host={{ inventory_hostname }}
                    state=started
                    delay=15
                    timeout=300

      sudo: false
